### ISSUE TITLE
Did you get further on solving this issue?

### ISSUE THREAD

**Issue by vongohren** [wKovacs64/tsdx-treeshaking-test#4]
I just wonder if you got any further on solving this issue?
Since the code is still a test, did you maybe find a way to do it outside?

**Comment by wKovacs64** [comment]
Hi. This entire repository (`tsdx-treeshaking-test`) was created to demonstrate an issue I ran into in another project (if that's what you were referring to by "since the code is still a test"?).

After some discussion with some much smarter folks, they showed me it that in this particular case, it was Emotion's fault that it wasn't being removed from the bundle properly and there was nothing tsdx could do about it ("working as intended", as it were). There's also some work going on in tsdx regarding multiple entries yielding multiple outputs which should improve the tree-shaking story, but I'm not up to date on it.

Does that help?

**Comment by vongohren** [comment]
@wKovacs64 yes thanks it helps alot :)
Yeah I was more refering to that you created a test repo, and its 9 months ago, I would guess you either solved it or moved along but did not do anything with this repo.

But you informed me well :)

**Comment by wKovacs64** [comment]
Yeah I just left it here for historical purposes. I will archive it so that it's more clear. Thanks! :)
